### ISSUE TITLE
`ut n items` throwing

### ISSUE THREAD

**Issue by BenPH** [sassoftware/jsl-hamcrest#111]
I noticed on master that `ut n items` is throwing an error that `N Items` doesn't have enough arguments. It seems it's caused by the change to use `Builtin` in the `UtSizeMatcher` https://github.com/sassoftware/jsl-hamcrest/commit/5395c1d1e4a80ac177a5776cbe46578bd8f68970 but I'm not sure why.

As an example:
```
uttest("SizeTests", "N Items", expr(
	ut assert that(expr({1,2,3}), ut n items(3))
));
```
Which gives:
```
FAILURE  Test #153: {1, 2, 3} n items equal to 3 (SizeTests ⮚ N Items ⮚ 1) 
         Actual: threw "Error: not enough arguments. 1 time. N Items /*###*/()"
       Expected: n items equal to 3
```

**Comment by BenPH** [comment]
Looks like it affects `ut length` too.

**Comment by JustinChilton** [comment]
Here is a simple reproduction. Looks like a possible issue with JMP that we did not see with `NRow`.
```
fn = parse("Builtin:n items");
fn({1, 2, 3});
```

```
not enough arguments in access or evaluation of 'N Items' , N Items/*###*/()
```

Edit: or even simpler
```
fn = Expr( N Items() );
fn( {1, 2, 3} );
```
