### ISSUE TITLE
Run subset of tests

### ISSUE THREAD

**Issue by himanga** [sassoftware/jsl-hamcrest#130]
I'm not sure of the best way to do this, so I am looking for ideas before working on a solution.

It would be nice to skip certain (normally slow running) tests most of the time.  Tests for applications that communicate with other systems need to include some tests that actually get data, which means running tests can take a few minutes.  This makes running tests feel like a burden and they aren't run as often while coding.  Today I split those long running tests into separate folders but that is a lot more work than if I could include some flag or category when calling a matcher or defining a test, and then have an option to run all tests or just fast ones.

Has anyone found a solution or have ideas on how to approach this with jsl-hamcrest?

Thanks!

**Comment by emccorkle** [comment]
I think that splitting into folders is a tried and true solution. Especially when combined with a driver file that could `Include` test files from the "fast" directory and conditionally `Include` the slow tests.

Another option might be to use `<<SkipIf` like:
```
skip slow tests = 1;

Add Tests = ut test case("Add") << SkipIf(Expr(skip slow tests));
ut test(Add Tests, "1 + 1", Expr(
    Wait(5);
    ut assert that(Expr(1 + 1), 2)
));
```

**Comment by himanga** [comment]
Ah ha! Shame on me for missing that in the change log, `skip if` will work great. Thank you!

I believe the driver file you mentioned is essentially what I am doing today, and for some projects that works great, but now I have the solution for 'the rest' of them.
