### ISSUE TITLE
Confusing error message when comparing matrix

### ISSUE THREAD

**Issue by BenPH** [sassoftware/jsl-hamcrest#135]
I mistakenly was entering a matrix in a test checking a value is less than or equal to another and I was confused by the error message until I caught my mistake. Maybe a check for a matrix is necessary. 

```jsl
NamesDefaultToHere(0);
ut global reporter = ut streaming log reporter with skip();
m = [1, 2, 3];
ut assert that(Expr(m), ut less than or equal to(3));
```

```
FAILURE  Test #1: m less than or equal to 3 () 
         Actual: the UtOrderingComparisonMatcher failed to return success/failure info. the matcher itself is broken, not the test.
       Expected: less than or equal to 3
0
```

**Comment by himanga** [comment]
I don't remember if it was from a matrix but I also got this error message at some point.

**Comment by nrclark38258** [comment]
@BenPH I've never seen this message, but I am curious what the `ut streaming log reporter with skip()` offers vs the standard reporter(s)

**Comment by BenPH** [comment]
> @BenPH I've never seen this message, but I am curious what the `ut streaming log reporter with skip()` offers vs the standard reporter(s)

I was just working off an example from the scripting index. Any reporter will do. But looking at https://github.com/sassoftware/jsl-hamcrest/blob/265dbe5c79d5d4a75d670d9bfdf5d271a5854d67/Source/Reporters/StreamingLogReporter.jsl it is a reporter that writes results to the JMP log including any skipped tests.

**Comment by emccorkle** [comment]
@nrclark38258 The `ut streaming log reporter with skip()` was added in 2.0.0 and allows the streaming reporter to show skipped tests and assertions. It enables `write skips?` in https://github.com/sassoftware/jsl-hamcrest/blob/265dbe5c79d5d4a75d670d9bfdf5d271a5854d67/Source/Reporters/StreamingLogReporter.jsl#L41-L54 The previous `ut streaming log reporter` just doesn't show those and we didn't want to break that behavior so a new factory was added.

**Comment by nrclark38258** [comment]
Excellent, thank you both! I'll have to poke around with that one. I've done some editing to the Collecting reporter, but haven't dug into the other ones much.

**Comment by emccorkle** [comment]
As for the original issue, I definitely think we should be showing a better error message for this. We shouldn't be showing `the matcher itself is broken` in this case.
