### ISSUE TITLE
JUnit Reporter

### ISSUE THREAD

**Issue by VDFaller** [sassoftware/jsl-hamcrest#56]
I'd like to have a reporter for JUnit.  We've already created it.  Would you recommend putting it in reporters or the new custom folder?

**Comment by emccorkle** [comment]
If you want to contribute back here, please put it in [/Source/Reporters](https://github.com/sassoftware/jsl-hamcrest/tree/master/Source/Reporters). The [/Source/Reporters/Custom](https://github.com/sassoftware/jsl-hamcrest/tree/master/Source/Reporters/Custom) folder is for local Reporters that are not part of released jsl-hamcrest. All files in that folder are ignored by git.

**Comment by VDFaller** [comment]
@dougiechong Can you put the JUnit reporter in here?
