### ISSUE TITLE
Add more documentation about using reporters

### ISSUE THREAD

**Issue by JustinChilton** [sassoftware/jsl-hamcrest#95]
There was a [question on the JMP User Community](https://community.jmp.com/t5/Discussions/JSL-Hamcrest-reporting/m-p/238031) about changing the default reporter. I don't think we have much documentation on this, or at all, so it would be good to add something in the readme or the generated docs.
Should we also document some of the reporter factory functions with examples?

**Comment by nrclark38258** [comment]
I think that would be good. I have utilized some of the reporter features kind of how they seem to be intended, but I slowly digested the code to 'make it work for me', but better / more documentation would be great!
